services:
  - type: web
    name: fof-schedule-api
    env: node
    buildCommand: npm install && npm run build && npm run db:generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fof-schedule-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  - name: fof-schedule-db
    databaseName: fof_schedule
    user: fof_user